version: 2
jobs:
  deploy_dev:
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install --unsafe
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy to Github Pages
          command: npm run deploy

workflows:
  version: 2
  deploy_dev:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: master
